name: ctp
description: "A Truck Trading application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.8+14

environment:
  sdk: ">=3.4.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  appinio_swiper: ^2.1.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.2.0
  cloud_functions: ^5.3.4
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  file_picker: ^8.0.6
  firebase_app_check: ^0.3.0+4
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^19.0.0
  flutter_pdfview: ^1.3.4
  flutter_portal: ^1.1.3
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_geocoding_api: ^1.5.2
  google_maps_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  hash_cached_image: ^0.0.2
  html: ^0.15.5
  html_view: ^0.0.3
  http: ^1.1.0
  image: ^4.3.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  image_zoomer: ^0.0.3
  intl: ^0.19.0
  mime_type: ^1.0.0
  open_file: ^3.5.10
  path: any
  path_provider: ^2.1.5
  pdf: ^3.11.1
  pdfx: ^2.8.0
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.1.2
  share_plus: ^10.0.0
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^27.2.5
  table_calendar: ^3.1.2
  timezone: ^0.10.0
  ulid: ^2.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.1.10
  url_strategy: ^0.3.0
  webview_flutter: ^4.10.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/HeroImageLoginPage.png
    - lib/assets/CTPLogo.png
    - lib/assets/CountryCodes.json
    - lib/assets/truckSelectImage.png
    - lib/assets/tutorialImage.png
    - lib/assets/HomePageHero.png
    - lib/assets/default-profile-photo.jpg
    - lib/assets/trailer_image.jpeg
    - lib/assets/truck_image.jpeg
    - lib/assets/default_vehicle_image.png
    - lib/assets/verified_Icon.png
    - lib/assets/shaking_hands.png
    - lib/assets/Offer_SummaryImage.png
    - lib/assets/WishListImage.png
    - lib/assets/HeartVector.png
    - lib/assets/fonts/Roboto-Bold.ttf
    - lib/assets/fonts/Roboto-Regular.ttf
    - lib/assets/country-by-name.json
    - lib/assets/Layer_1.png
    - lib/assets/Layer_2.png
    - lib/assets/Logo/ASHOK LEYLAND.png
    - lib/assets/Logo/CNHTC.png
    - lib/assets/Logo/DAF.png
    - lib/assets/Logo/DAYUN.png
    - lib/assets/Logo/EICHER.png
    - lib/assets/Logo/FAW.png
    - lib/assets/Logo/FIAT.png
    - lib/assets/Logo/FORD.png
    - lib/assets/Logo/FOTON.png
    - lib/assets/Logo/FUSO.png
    - lib/assets/Logo/HINO.png
    - lib/assets/Logo/HYUNDAI.png
    - lib/assets/Logo/ISUZU.png
    - lib/assets/Logo/IVECO.png
    - lib/assets/Logo/JAC.png
    - lib/assets/Logo/JOYLONG.png
    - lib/assets/Logo/MAN.png
    - lib/assets/Logo/MERCEDES BENZ.png
    - lib/assets/Logo/PEUGEOT.png
    - lib/assets/Logo/POWERSTAR.png
    - lib/assets/Logo/RENAULT.png
    - lib/assets/Logo/SCANIA.png
    - lib/assets/Logo/TATA.png
    - lib/assets/Logo/TOYOTA.png
    - lib/assets/Logo/UD TRUCKS.png
    - lib/assets/Logo/VOLVO.png
    - lib/assets/Logo/VW.png
    - lib/assets/Loading_Logo_CTP.gif
    - lib/assets/dealer_handshake.png
    - lib/assets/transporter_handshake.png
    - lib/assets/LoginImageWeb.png
    - lib/assets/Freightliner-logo-6000x2000.png
    - lib/assets/countries.json
    - lib/assets/updated_truck_data.json
    - lib/assets/version.json
    - lib/assets/CTPLOGO3.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: lib/assets/fonts/Roboto-Bold.ttf
  #       - asset: lib/assets/fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/CTPLogo.png" # Update the path if your icon is located elsewhere
