// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6C6DRdzG674nFLiRJYugQ8hRlHUp8T0I',
    appId: '1:656287296553:web:75f8a76bd7a63a96408038',
    messagingSenderId: '656287296553',
    projectId: 'ctp-central-database',
    authDomain: 'ctp-central-database.firebaseapp.com',
    storageBucket: 'ctp-central-database.appspot.com',
    measurementId: 'G-0TKBWWE0ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq8BvGszbHrF6_Gi-j9Vy947McQQFkTM',
    appId: '1:656287296553:android:b819f014d9cb2161408038',
    messagingSenderId: '656287296553',
    projectId: 'ctp-central-database',
    storageBucket: 'ctp-central-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqL1QZNODYI3WVLeclgK3I6QlA37aQ3E',
    appId: '1:656287296553:ios:2f83e65294413a11408038',
    messagingSenderId: '656287296553',
    projectId: 'ctp-central-database',
    storageBucket: 'ctp-central-database.appspot.com',
    iosBundleId: 'com.example.ctp',
  );
}
